### PR TITLE
refactor: Add config.json file to project

### PR DESCRIPTION
**Pull request by AlexandreResende**
Add config.json file to insert all static information from 
the application in this file. 
This way we can centralize all the data needed to run 
the app in only on file and require it when needed.

### CODE REVIEW

**Comment by lunzhang** [comment]
Hi, thanks for contributing!  I think it's better to move the routes folder inside server, so everything server sided is in there.  Also it's not necessary to add the ${__dirname} in the require.

**Comment by AlexandreResende** [comment]
Thanks for the response. I just modularized the routes for better maintainability of the code and the ${__dirname} because my boss told me  that some server may not find a resource based on the relative path.

**Comment by lunzhang** [comment]
Hi, modularizing the routes is fine but could you move the routes folder inside the server directory then all server sided stuff would be inside the directory.  Also according to this https://stackoverflow.com/questions/8131344/what-is-the-difference-between-dirname-and-in-node-js ,  ./ would **always** be relative to the file in which its called.

**Comment by AlexandreResende** [comment]
Sent a PR that moved the routes folder inside the server folder.

**Comment by lunzhang** [comment]
Merged!  Thanks for contributing! :)

**Pull request merged**
